name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Setup node js env
      - name: Set up node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      # Install all packages (better way is to use `npm ci`)
      - name: Install dependencies
        run: npm install

      # Run all tests
      - name: Test the monorepo
        run: npm run test

      # Build all packages
      - name: Build the monorepo
        run: npm run build

      # Deploy the client
      - name: Deploy the Client to AWS S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ vars.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          SOURCE_DIR: './packages/client/build'

      # Prepare API Deployment (it`s important to exclude node_modules)
      - name: Generate deployment package for API Backend
        run: cd ./packages/api && zip -r ./../../deploy-api.zip ./ -x "node_modules/*" && cd -

      # Deploy the API
      - name: Deploy the API Backend package to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@master
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ vars.AWS_BS_APPLICATION }}
          environment_name: ${{ vars.AWS_BS_ENVIRONMENT }}
          version_label: ${{ github.run_number }}
          region: ${{ vars.AWS_REGION }}
          deployment_package: deploy-api.zip
